---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: backend
    labels:
        app: backend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            name: backend
            labels:
                app: backend
            
        spec:
            containers:
            -   name: backend
                image: hub.example.com/shop-backend:1.0.0
                ports:
                -   name: backend
                    containerPort: 3000
                livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 3000
                    initialDelaySeconds: 10
                readinessProbe:
                    httpGet:
                        path: /
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 1
                    failureThreshold: 2